packages:
  - apps/*
  - packages/*
  - "!packages/cli-old"
  - "!packages/tmp"
  - packages/typegen/web
allowBuilds:
  "@parcel/watcher": true
  "@prisma/client": true
  "@prisma/engines": true
  core-js: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
blockExoticSubdeps: true
overrides:
  '@next/env': npm:@varlock/nextjs-integration@^1.1.0
  shiki: 3.13.0
  '@shikijs/types': 3.13.0
  glob: ^11.1.0
  '@modelcontextprotocol/sdk': ^1.25.2
  preact: ^10.26.10
  qs: ^6.14.1
  vite: ^6.4.1
  body-parser: ^2.2.1
autoInstallPeers: true
packageConfigs:
  '@proofkit/fmdapi':
    engineStrict: true
