/**
 * Generated by @proofkit/typegen package
 * https://proofkit.dev/docs/typegen
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */
import { DataApi, FmHttpAdapter } from "@proofkit/fmdapi";
import { Zcontacts } from "../contacts";
if (!process.env.FM_HTTP_BASE_URL)
  throw new Error("Missing env var: FM_HTTP_BASE_URL");
if (!process.env.FM_CONNECTED_FILE_NAME)
  throw new Error("Missing env var: FM_CONNECTED_FILE_NAME");

export const client = DataApi({
  adapter: new FmHttpAdapter({
    baseUrl: process.env.FM_HTTP_BASE_URL,
    connectedFileName: process.env.FM_CONNECTED_FILE_NAME,
    scriptName: "execute_data_api",
  }),
  layout: "Contacts",
  schema: { fieldData: Zcontacts },
});
