/**
 * Generated by @proofkit/typegen package
 * https://proofkit.dev/docs/typegen
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overwritten
 */
import { DataApi } from "@proofkit/fmdapi";
import { WebViewerAdapter } from "@proofkit/webviewer/adapter";
import { Zcontacts } from "../contacts";

export const client = DataApi({
  adapter: new WebViewerAdapter({ scriptName: "execute_data_api" }),
  layout: "Contacts",
  schema: { fieldData: Zcontacts },
});
